openapi: 3.0.0
info:
  title: GenTwo
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  /:
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples: {}
      operationId: get
      description: APIドキュメントをHTML形式で取得します。
      parameters: []
  '/get/user/posts/{postId}':
    parameters:
      - schema:
          type: string
        name: postId
        in: path
        required: true
    get:
      summary: '/get/posts/{postId}'
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  textBody:
                    type: string
                  reactions:
                    type: array
                    items:
                      type: object
                      properties:
                        emoji:
                          type: string
                        user:
                          $ref: '#/components/schemas/userId'
                  imageLink:
                    type: string
              examples:
                example-1:
                  value:
                    textBody: 猫ちゃんかわいい
                    reactions:
                      - emoji: bowing_man
                        user:
                          id: Chaha1n
                          bio: 豊田高専の２年生です。
                          icon: 'https://iconserver.com/chaha1n'
                    imageLink: 'https://imageserver/com/hash1'
      operationId: get-posts-postId
      description: 指定された投稿IDの投稿の詳細を取得する。
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              example-1:
                value: {}
        description: ''
  '/get/user/profile/{userId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      summary: '/get/profile/{userId}'
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/detailedUserModel'
              examples:
                chaha1n:
                  value:
                    id: chaha1n
                    birth: '2002-07-18'
                    followNumber: 10000
                    followersNumber: 0
                    location: NITTC
                    bio: 自己紹介文
                    createdAt: '1970-01-01'
                    icon: 'https://iconserver.com/chaha1n'
      operationId: get-get-profile-userId
      description: 指定されたユーザーIDの詳細なプロフィール情報を返却する。
  '/post/user/reaction/{postId}':
    parameters:
      - schema:
          type: string
        name: postId
        in: path
        required: true
    post:
      summary: ''
      operationId: post-post-user-reaction-postId
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                '':
                  $ref: '#/components/schemas/authUserModel'
                emojiId:
                  type: string
  /post/user/post:
    post:
      summary: ''
      operationId: post-post-user-post
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    type: string
      description: 投稿を行います。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  $ref: '#/components/schemas/authUserModel'
                post:
                  type: string
  /login:
    post:
      summary: ''
      operationId: post-login
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/authUserModel'
components:
  schemas:
    detailedUserModel:
      title: detailedUser
      type: object
      description: ''
      x-examples: {}
      properties:
        id:
          description: Unique identifier for the given user.
          type: string
        birth:
          type: string
        followNumber:
          type: integer
        followersNumber:
          type: integer
        location:
          type: string
        bio:
          type: string
        createdAt:
          type: string
        icon:
          type: string
      required:
        - id
    userId:
      title: userId
      type: object
      properties:
        id:
          type: string
      x-examples:
        example-1:
          id: string
    authUserModel:
      title: authUserModel
      type: object
      properties:
        userId:
          type: string
        token:
          type: string
